steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/webaf01357/image-processor', '.']
images:
- 'gcr.io/$PROJECT_ID/github.com/webaf01357/image-processor'
options:
  logging: CLOUD_LOGGING_ONLY
